var mongoose = require('mongoose');

var CoySchema = new mongoose.Schema({
    ID: Number,
    Name: String,
    CurrencySymbol: String,
    CurrencyDecimalDigits: Number,
    NumberDecimalDigits: Number,
    DecimalSeparator: String,
    HoursDecimalDigits: Number,
    ItemCostPriceDecimalDigits: Number,
    ItemSellingPriceDecimalDigits: Number,
    PostalAddress1: String,
    PostalAddress2: String,
    PostalAddress3: String,
    PostalAddress4: String,
    PostalAddress5: String,
    GroupSeparator: String,
    RoundingValue: Number,
    TaxSystem: Number,
    RoundingType: Number,
    AgeMonthly: Boolean,
    DisplayInactiveItems: Boolean,
    WarnWhenItemCostIsZero: Boolean,
    WarnWhenItemQuantityIsZero: Boolean,
    WarnWhenItemSellingBelowCost: Boolean,
    CountryId: Number,
    CompanyEntityTypeId: Number,
    TakeOnBalanceDate: Date,
    EnableCustomerZone: Boolean,
    EnableAutomaticBankFeedRefresh: Boolean,
    ContactName: String,
    Telephone: String,
    Fax: String,
    Mobile: String,
    Email: String,
    IsPrimarySendingEmail: Boolean,
    PostalAddress01: String,
    PostalAddress02: String,
    PostalAddress03: String,
    PostalAddress04: String,
    PostalAddress05: String,
    CompanyInfo01: String,
    CompanyInfo02: String,
    CompanyInfo03: String,
    CompanyInfo04: String,
    CompanyInfo05: String,
    IsOwner: Boolean,
    UseCCEmail: Boolean,
    CCEmail: String,
    CheckForDuplicateCustomerReferences: Boolean,
    CheckForDuplicateSupplierReferences: Boolean,
    DisplayName: String,
    DisplayInactiveCustomers: Boolean,
    DisplayInactiveSuppliers: Boolean,
    DisplayInactiveTimeProjects: Boolean,
    LockProcessing: Boolean,
    LockProcessingDate: Date,
    LockTimesheetProcessing: Boolean,
    LockTimesheetProcessingDate: Date,
    TaxPeriodFrequency: Number,
    PreviousTaxPeriodEndDate: Date,
    PreviousTaxReturnDate: Date,
    UseNoreplyEmail: Boolean,
    AgeingBasedOnDueDate: Boolean,
    UseLogoOnEmails: Boolean,
    UseLogoOnCustomerZone: Boolean,
    City: String,
    State: String,
    Country: String,
    HomeCurrencyId: Number,
    CurrencyId: Number,
    Created: Date,
    Modified: Date,
    Active: Boolean,
    TaxNumber: String,
    RegisteredName: String,
    RegistrationNumber: String,
    IsPracticeAccount: Boolean
})

module.exports = mongoose.model('CoySchema')


/* From https://accounting.sageone.co.za/api/1.1.1/Help/Api/GET-Company-Get-id

 Sample:

{
  "ID": 1,
  "Name": "sample string 2",
  "CurrencySymbol": "sample string 3",
  "CurrencyDecimalDigits": 4,
  "NumberDecimalDigits": 5,
  "DecimalSeparator": "sample string 6",
  "HoursDecimalDigits": 7,
  "ItemCostPriceDecimalDigits": 8,
  "ItemSellingPriceDecimalDigits": 9,
  "PostalAddress1": "sample string 10",
  "PostalAddress2": "sample string 11",
  "PostalAddress3": "sample string 12",
  "PostalAddress4": "sample string 13",
  "PostalAddress5": "sample string 14",
  "GroupSeparator": "sample string 15",
  "RoundingValue": 16,
  "TaxSystem": 0,
  "RoundingType": 0,
  "AgeMonthly": true,
  "DisplayInactiveItems": true,
  "WarnWhenItemCostIsZero": true,
  "WarnWhenItemQuantityIsZero": true,
  "WarnWhenItemSellingBelowCost": true,
  "CountryId": 22,
  "CompanyEntityTypeId": 1,
  "TakeOnBalanceDate": "2016-12-15",
  "EnableCustomerZone": true,
  "EnableAutomaticBankFeedRefresh": true,
  "ContactName": "sample string 25",
  "Telephone": "sample string 26",
  "Fax": "sample string 27",
  "Mobile": "sample string 28",
  "Email": "sample string 29",
  "IsPrimarySendingEmail": true,
  "PostalAddress01": "sample string 31",
  "PostalAddress02": "sample string 32",
  "PostalAddress03": "sample string 33",
  "PostalAddress04": "sample string 34",
  "PostalAddress05": "sample string 35",
  "CompanyInfo01": "sample string 36",
  "CompanyInfo02": "sample string 37",
  "CompanyInfo03": "sample string 38",
  "CompanyInfo04": "sample string 39",
  "CompanyInfo05": "sample string 40",
  "IsOwner": true,
  "UseCCEmail": true,
  "CCEmail": "sample string 42",
  "CheckForDuplicateCustomerReferences": true,
  "CheckForDuplicateSupplierReferences": true,
  "DisplayName": "sample string 47",
  "DisplayInactiveCustomers": true,
  "DisplayInactiveSuppliers": true,
  "DisplayInactiveTimeProjects": true,
  "LockProcessing": true,
  "LockProcessingDate": "2016-12-15",
  "LockTimesheetProcessing": true,
  "LockTimesheetProcessingDate": "2016-12-15",
  "TaxPeriodFrequency": 1,
  "PreviousTaxPeriodEndDate": "2016-12-15",
  "PreviousTaxReturnDate": "2016-12-15",
  "UseNoreplyEmail": true,
  "AgeingBasedOnDueDate": true,
  "UseLogoOnEmails": true,
  "UseLogoOnCustomerZone": true,
  "City": "sample string 57",
  "State": "sample string 58",
  "Country": "sample string 59",
  "HomeCurrencyId": 1,
  "CurrencyId": 1,
  "Created": "2016-12-15",
  "Modified": "2016-12-15",
  "Active": true,
  "TaxNumber": "sample string 62",
  "RegisteredName": "sample string 63",
  "RegistrationNumber": "sample string 64",
  "IsPracticeAccount": true
}


*/